### ISSUE TITLE
Migrate Detect Language 

### ISSUE THREAD

**Issue by abpai94** [ltb-project/ltb-common#19]
The following classes contain duplicate code:
https://github.com/ltb-project/service-desk/blob/master/lib/detectbrowserlanguage.php
https://github.com/ltb-project/self-service-password/blob/master/lib/detectbrowserlanguage.php
https://github.com/ltb-project/white-pages/blob/master/lib/detectbrowserlanguage.php

These can be migrated to create a new addition to the library to reduce duplication.

**Comment by davidcoutadeur** [comment]
I agree that the code could be factorized, but not in ltb-ldap.

The remaining question is: do we create a dedicated project for just one function? Not sure, except if we have other things to factorize.

**Comment by davidcoutadeur** [comment]
> We already use LTB LDAP for mail functions, so for me it is ok to add languages functions

Indeed, there are other classes in this library. We should rename the library to reflect the real usage. For example, something like `ltb-common`

**Comment by davidcoutadeur** [comment]
> The following classes contain duplicate code: https://github.com/ltb-project/service-desk/blob/master/lib/detectbrowserlanguage.php https://github.com/ltb-project/self-service-password/blob/master/lib/detectbrowserlanguage.php https://github.com/ltb-project/white-pages/blob/master/lib/detectbrowserlanguage.php
> 
> These can be migrated to create a new addition to the library to reduce duplication.

Please also open an issue for all projects that need refactoring (if not already done): ssp, service-desk, and white-pages. Just to be sure we don't forget.
