### ISSUE TITLE
Add page size parameter to LDAP connection

### ISSUE THREAD

**Issue by coudot** [ltb-project/ltb-common#30]
For Active Directory we need to use the page size settings, else we will not be able to list all entries.

**Comment by davidcoutadeur** [comment]
Should be ok with PR: #42 

For now, I think searching multiple entries:
* is not done at all in self-service-password
* is done only in Ltb\Ldap\search function, which I have configured to use paged search

We should keep this is mind while adding more search functions in ltb-common or ssp/service-desk.

TODO:

- [ ] add the corresponding test for paged search
